// ============================================================
// SELECTOR ENGINE
// Generates stable, shadow-piercing CSS selectors for any DOM element.
// Must be standalone — no dependencies on other capture files.
// Phase 1 — most critical file, must be correct before anything else.
// ============================================================

export interface SelectorResult {
  selector: string;
  shadowPiercing: boolean;
  confidence: 'high' | 'medium' | 'low';
}

/**
 * Generate the most stable selector for a given element.
 * Priority: data-testid > id > aria-label > role+text > structural path
 */
export function generateSelector(element: Element): SelectorResult {
  // 1. data-testid (most stable, devs put these for testing)
  const testId = element.getAttribute('data-testid') || element.getAttribute('data-test-id') || element.getAttribute('data-cy');
  if (testId) {
    return { selector: `[data-testid="${CSS.escape(testId)}"]`, shadowPiercing: false, confidence: 'high' };
  }

  // 2. Unique ID (only if it doesn't look auto-generated)
  const id = element.id;
  if (id && !isAutoGeneratedId(id)) {
    return { selector: `#${CSS.escape(id)}`, shadowPiercing: false, confidence: 'high' };
  }

  // 3. aria-label on interactive elements
  const ariaLabel = element.getAttribute('aria-label');
  const role = element.getAttribute('role') || inferRole(element);
  if (ariaLabel && role) {
    return { selector: `[role="${role}"][aria-label="${CSS.escape(ariaLabel)}"]`, shadowPiercing: false, confidence: 'high' };
  }

  // 4. Name attribute (form inputs)
  const name = element.getAttribute('name');
  if (name && isFormElement(element)) {
    const tag = element.tagName.toLowerCase();
    return { selector: `${tag}[name="${CSS.escape(name)}"]`, shadowPiercing: false, confidence: 'high' };
  }

  // 5. Structural path — walk up the DOM
  const path = buildStructuralPath(element);
  const isShadow = isInsideShadowRoot(element);

  return {
    selector: path,
    shadowPiercing: isShadow,
    confidence: path.includes(':nth-child') ? 'low' : 'medium',
  };
}

function buildStructuralPath(element: Element): string {
  const parts: string[] = [];
  let current: Element | null = element;

  while (current && current !== document.documentElement) {
    const root = current.getRootNode();
    const host: Element | null = root instanceof ShadowRoot ? root.host : null;

    if (host) {
      // We're inside a shadow root — add shadow boundary marker and continue from host
      parts.unshift(getElementPart(current));
      parts.unshift('::shadow');
      current = host;
      continue;
    }

    parts.unshift(getElementPart(current));
    current = current.parentElement;
  }

  return parts.join(' > ');
}

function getElementPart(element: Element): string {
  const tag = element.tagName.toLowerCase();
  const id = element.id;

  if (id && !isAutoGeneratedId(id)) return `${tag}#${CSS.escape(id)}`;

  const classes = Array.from(element.classList)
    .filter(c => !isAutoGeneratedClass(c))
    .slice(0, 2)
    .map(c => `.${CSS.escape(c)}`)
    .join('');

  if (classes) {
    const siblings = element.parentElement
      ? Array.from(element.parentElement.querySelectorAll(`${tag}${classes}`))
      : [];
    if (siblings.length === 1) return `${tag}${classes}`;
  }

  // Fall back to nth-child
  const parent = element.parentElement;
  if (parent) {
    const index = Array.from(parent.children).indexOf(element) + 1;
    return `${tag}:nth-child(${index})`;
  }

  return tag;
}

function isAutoGeneratedId(id: string): boolean {
  // Heuristic: auto-generated IDs often contain long random strings or are purely numeric
  return /^[0-9]+$/.test(id) || /[a-f0-9]{8,}/.test(id) || id.length > 50;
}

function isAutoGeneratedClass(cls: string): boolean {
  // Tailwind-style and CSS module hashes
  return /^[a-z]{1,3}-[a-f0-9]{4,}$/.test(cls) || /css-[a-f0-9]+/.test(cls) || cls.length > 40;
}

function isFormElement(element: Element): boolean {
  return ['input', 'select', 'textarea', 'button'].includes(element.tagName.toLowerCase());
}

function inferRole(element: Element): string | null {
  const tag = element.tagName.toLowerCase();
  const roleMap: Record<string, string> = {
    button: 'button', a: 'link', input: 'textbox', select: 'combobox',
    textarea: 'textbox', nav: 'navigation', main: 'main', header: 'banner',
  };
  return roleMap[tag] || null;
}

function isInsideShadowRoot(element: Element): boolean {
  let root = element.getRootNode();
  return root instanceof ShadowRoot;
}

/**
 * Recursively search through shadow roots to find an element matching a selector.
 * Used during demo/overlay playback to locate elements by stored selector.
 */
export function queryShadowPiercing(selector: string, root: Document | ShadowRoot = document): Element | null {
  // Try direct query first
  const direct = root.querySelector(selector);
  if (direct) return direct;

  // Search all shadow roots
  const allElements = root.querySelectorAll('*');
  for (const el of Array.from(allElements)) {
    if (el.shadowRoot) {
      const found = queryShadowPiercing(selector, el.shadowRoot);
      if (found) return found;
    }
  }

  return null;
}
