-- Seed six built-in global featured templates (one per persona category)
-- sessionJsonKey values are placeholders to be replaced with real R2 content
INSERT INTO templates (id, workspaceId, createdBy, title, description, category, isGlobal, isFeatured, usageCount, thumbnailUrl, sessionJsonKey, createdAt, updatedAt) VALUES
  (
    'tmpl_feature_walkthrough',
    NULL,
    NULL,
    'Feature Walkthrough — PM Edition',
    'Built for PMs who ship weekly. Structured chapters, stakeholder-ready narration, and a cinematic output your team will actually watch.',
    'feature-walkthrough',
    1,
    1,
    0,
    NULL,
    'templates/seed/feature-walkthrough/session.json',
    1748649600000,
    1748649600000
  ),
  (
    'tmpl_client_onboarding',
    NULL,
    NULL,
    'Client Onboarding — CS Team',
    'Your fastest path from new customer to confident user. Warm tone, clear steps, and callouts on every confusing UI moment.',
    'client-onboarding',
    1,
    1,
    0,
    NULL,
    'templates/seed/client-onboarding/session.json',
    1748649600000,
    1748649600000
  ),
  (
    'tmpl_design_handoff',
    NULL,
    NULL,
    'Design Handoff — Engineering Ready',
    'Dense, precise, and built for engineers who read before they build. Component specs, interaction states, and zero ambiguity.',
    'design-handoff',
    1,
    1,
    0,
    NULL,
    'templates/seed/design-handoff/session.json',
    1748649600000,
    1748649600000
  ),
  (
    'tmpl_process_runbook',
    NULL,
    NULL,
    'Process Runbook — Ops Standard',
    'The SOP your team will actually follow six months from now. Formal structure, clear ownership, and built to be updated without pain.',
    'process-runbook',
    1,
    1,
    0,
    NULL,
    'templates/seed/process-runbook/session.json',
    1748649600000,
    1748649600000
  ),
  (
    'tmpl_product_demo',
    NULL,
    NULL,
    'Product Demo — Sales Narrative',
    'Turn your product tour into a sales asset. Problem, solution, key features, call to action. Ready for the pricing page or the cold email.',
    'product-demo',
    1,
    1,
    0,
    NULL,
    'templates/seed/product-demo/session.json',
    1748649600000,
    1748649600000
  ),
  (
    'tmpl_quick_howto',
    NULL,
    NULL,
    'Quick How-To — 5 Minutes',
    'For the process you do every week but have never documented. Five to eight steps, plain language, done before your next meeting.',
    'quick-howto',
    1,
    1,
    0,
    NULL,
    'templates/seed/quick-howto/session.json',
    1748649600000,
    1748649600000
  );
